package com.springboot.mybatis.orm.dao;

import com.springboot.mybatis.orm.model.PmsProduct;
import com.springboot.mybatis.orm.model.PmsProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PmsProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    long countByExample(PmsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    int deleteByExample(PmsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    int insert(PmsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    int insertSelective(PmsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    List<PmsProduct> selectByExampleWithBLOBs(PmsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    List<PmsProduct> selectByExample(PmsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    PmsProduct selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    int updateByExampleSelective(@Param("record") PmsProduct record, @Param("example") PmsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") PmsProduct record, @Param("example") PmsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    int updateByExample(@Param("record") PmsProduct record, @Param("example") PmsProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    int updateByPrimaryKeySelective(PmsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(PmsProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pms_product
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    int updateByPrimaryKey(PmsProduct record);
}