package com.springboot.mybatis.orm.model;

import java.io.Serializable;
import java.util.Date;

public class Student implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.id
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.t_id
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    private Integer tId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.name
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.gender
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.create_date
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.inset_date
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    private Date insetDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table student
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.id
     *
     * @return the value of student.id
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.id
     *
     * @param id the value for student.id
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.t_id
     *
     * @return the value of student.t_id
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.t_id
     *
     * @param tId the value for student.t_id
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.name
     *
     * @return the value of student.name
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.name
     *
     * @param name the value for student.name
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.gender
     *
     * @return the value of student.gender
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.gender
     *
     * @param gender the value for student.gender
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.create_date
     *
     * @return the value of student.create_date
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.create_date
     *
     * @param createDate the value for student.create_date
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.inset_date
     *
     * @return the value of student.inset_date
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    public Date getInsetDate() {
        return insetDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.inset_date
     *
     * @param insetDate the value for student.inset_date
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    public void setInsetDate(Date insetDate) {
        this.insetDate = insetDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Mon Jan 04 15:37:40 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", tId=").append(tId);
        sb.append(", name=").append(name);
        sb.append(", gender=").append(gender);
        sb.append(", createDate=").append(createDate);
        sb.append(", insetDate=").append(insetDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}