spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/house?useUnicode=true&characterEncoding=utf-8&useSSL=false
    password: root
    username: root
mybatis:
  type-aliases-package: com.springboot.mybatis.orm.model
  mapper-locations: classpath:com.springboot.mybatis.orm.*/*.xml,classpath*:com.springboot.mybatis.orm.*/*.xm
  
